MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet34'
        OUT_CHANNELS:  [128,256,512,256,256,128]  # new resnet34
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 80000
    LR_STEPS: [20000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-2
    WARMUP_ITERS: 1500
OUTPUT_DIR: 'outputs/resnet34_crop'
DATASET_DIR: "/work/datasets"
