MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet34'
        # OUT_CHANNELS:  [1024,256,512,256,256,128]  # resnet50_wide (Jenny sin conf?)
        OUT_CHANNELS:  [1024,512,512,256,256,128]  # resnet50_wide (512 på nr 2)
        INPUT_CHANNELS: 3
    # ligger i default
    # PRIORS:
    #     # FEATURE_MAPS: [38, 19, 10, 5, 3, 1] # normal
    #     FEATURE_MAPS: [(30,40), (15,20), (8,10), (4,5), (2,3), (1,1)] # resized
INPUT:
    IMAGE_SIZE: (240,320)
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 20000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
    WARMUP_ITERS: 1500
OUTPUT_DIR: 'outputs/resnet50_wide'
DATASET_DIR: "/work/datasets"
