MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet34'
        #OUT_CHANNELS: [128, 256, 128, 128, 64, 64] # basic
        #OUT_CHANNELS: [512, 1024, 512, 256, 256, 256] # vgg
        #OUT_CHANNELS: [64,64,64,64,256,512,1024] # resnet50
        #OUT_CHANNELS: [1024,512,512,256,256,128] # Jennys resnet50 baby
        OUT_CHANNELS:  [256,512,256,256,128,64]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 20000
    LR_STEPS: [6000, 10000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-2
    WARMUP_ITERS: 1500
OUTPUT_DIR: 'outputs/wip34_mod_lr_init'
DATASET_DIR: "/work/datasets"
