MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet34'
        #PRETRAINED: False # basic and vgg
        PRETRAINED: True # inception, resnet50
        #OUT_CHANNELS: [128, 256, 128, 128, 64, 64] # basic
        #OUT_CHANNELS: [512, 1024, 512, 256, 256, 256] # vgg
        #OUT_CHANNELS: [32,32,64,80,192,256,288,288,768,768,768,768,768,1280,2048,2048] # inception
        #OUT_CHANNELS: [64,64,64,64,256,512,1024] # resnet50
        #OUT_CHANNELS: [1024,512,512,256,256,128] # Jennys resnet50 baby
        OUT_CHANNELS:  [256,512,256,256,128,64]
        #OUT_CHANNELS: [1280,512,512,256,256,128] # efficientNet b0
        #OUT_CHANNELS: [2048,512,512,256,256,128] # efficientNet b5
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: 300
    #IMAGE_SIZE: 299 # Inception expects 299
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 20000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/wip34'
DATASET_DIR: "/work/datasets"
