MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet34'
        OUT_CHANNELS: [128,256,512,256,256,128] # resnet34
        INPUT_CHANNELS: 3
INPUT:
    #IMAGE_SIZE: 300 # normal
    IMAGE_SIZE: (240,320)
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 80000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-2
    WARMUP_ITERS: 1500
OUTPUT_DIR: 'outputs/master_resized'
DATASET_DIR: "/work/datasets"
