MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet34'
        PRETRAINED: True
        OUT_CHANNELS: [256,512,512,256,256,128] # resnet34
        INPUT_CHANNELS: 3
INPUT:
    # IMAGE_SIZE: 300
    IMAGE_SIZE: (240,320)
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val",)
SOLVER:
    MAX_ITER: 60000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-2
OUTPUT_DIR: 'outputs/waymo_resnet34_resize'
DATASET_DIR: "/work/datasets"
