MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet34'
        OUT_CHANNELS: [256,512,512,256,256,128] # resnet34
        INPUT_CHANNELS: 3
      PRIORS:
        # FEATURE_MAPS: [38, 19, 10, 5, 3, 1] # normal
        FEATURE_MAPS: [(30,40), (15,20), (8,10), (4,5), (2,3), (1,1)] # resized
INPUT:
    # IMAGE_SIZE: 300 # normal
    IMAGE_SIZE: (240,320) # resized
DATASETS:
    TRAIN: ("waymo_train")
    TEST: ("waymo_val")
SOLVER:
    MAX_ITER: 80000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-2
OUTPUT_DIR: 'outputs/waymo_resnet34_resized'
DATASET_DIR: "/work/datasets"
